<?php
$mainDir = "/students/groups/cs3380f14grp18/public_html/";

require $mainDir . "/includes/header.php";
?>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis porttitor tortor. Donec imperdiet risus in augue consectetur, id congue ligula volutpat. Integer varius commodo nisl quis dictum. Curabitur consectetur vehicula urna et lobortis. Maecenas accumsan nisi erat, aliquet viverra nisi pulvinar eu. In libero arcu, ultricies quis neque sed, sollicitudin hendrerit odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut pellentesque aliquet tellus. Mauris in sapien mollis, ultrices elit id, fermentum arcu. Ut et bibendum lorem. In hac habitasse platea dictumst. Sed sit amet pulvinar tortor. Donec interdum tortor feugiat mi consequat interdum.</p>
<p>In non luctus diam. Sed metus tortor, laoreet nec mollis eget, blandit nec odio. Aenean volutpat convallis purus, vitae fermentum tortor mollis et. Ut nisl eros, tincidunt sed lobortis non, sodales in diam. Donec et eros lorem. Duis tincidunt erat sit amet tortor consectetur efficitur. Fusce tincidunt dui eu neque lobortis, id ultrices massa iaculis. Ut in ligula dolor. Nulla at elit tincidunt, tempor purus in, accumsan orci. Vestibulum egestas, sem ut posuere lobortis, est odio pharetra lorem, id sodales elit nisl ut purus. Aliquam erat volutpat. Sed vel justo ornare, pharetra magna id, commodo nunc. Nunc at nisi rutrum velit vestibulum elementum. Proin semper molestie auctor. Cras sed sollicitudin tortor. Curabitur sem mauris, mollis in risus ac, tincidunt tempus nisl.</p>
<p>Suspendisse tempor nisl tellus, a euismod nibh interdum quis. Pellentesque leo arcu, volutpat in neque sit amet, lacinia aliquet lectus. Nam velit odio, aliquet eget ultrices at, aliquet eget dui. Vestibulum ut sem efficitur, porttitor lorem id, tempor libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam justo sem, tincidunt a blandit eu, commodo in felis. Integer vel interdum felis. Etiam dapibus felis ac metus eleifend bibendum. Aenean diam magna, fringilla sit amet ante id, elementum suscipit lectus.</p>
<p>Nullam dictum arcu eget pellentesque aliquet. Curabitur scelerisque nulla nulla, in vehicula magna maximus id. Maecenas volutpat consequat felis. Mauris non rhoncus augue. Pellentesque faucibus urna dapibus, rhoncus est vel, convallis lorem. Cras vel bibendum massa, sed blandit purus. Cras ut augue aliquam leo luctus iaculis vel quis justo. Ut non tellus feugiat, interdum felis sed, convallis elit. Suspendisse potenti. Vestibulum blandit gravida ligula sed aliquet.</p>
<p>Aenean rutrum ante id felis elementum bibendum. Duis eget lectus molestie, tincidunt lacus et, auctor dolor. Etiam varius imperdiet urna. Fusce nec accumsan nisi, et porttitor ligula. Donec ut lectus eu magna feugiat viverra. Nulla nulla dui, bibendum eu facilisis id, fermentum ut lacus. Maecenas ornare ex urna, ut faucibus neque finibus sed.</p>
<p>Quisque vitae mattis justo, at ultrices orci. Mauris eget felis quis orci molestie porttitor a in augue. Integer molestie purus ut scelerisque ornare. Integer ut risus aliquam, posuere leo ut, consectetur lacus. Donec sapien nunc, lacinia nec ligula ac, posuere sodales sapien. Sed vulputate augue pretium quam feugiat semper. Quisque sagittis urna et rhoncus mollis. Etiam commodo mollis est sed vulputate. Nullam ornare est dolor, in fringilla neque fringilla in. Aliquam in libero id massa rhoncus sodales a at enim. Fusce orci urna, accumsan in hendrerit at, ullamcorper sit amet dui. Curabitur sit amet suscipit lectus. Donec ullamcorper turpis eget libero hendrerit posuere. Sed interdum ex nec justo mattis accumsan.</p>
<p>Proin dolor mauris, laoreet sed purus non, pharetra condimentum ipsum. Nullam erat justo, auctor sit amet suscipit a, ultrices a arcu. Donec eleifend orci nulla, eu finibus dolor finibus ac. Sed tristique leo id posuere pharetra. Curabitur tempus, eros eget varius tincidunt, sapien libero faucibus ante, in lacinia nulla diam sed eros. Ut rhoncus turpis tortor. Curabitur ut facilisis augue. Nam at nunc a diam malesuada posuere. Suspendisse justo arcu, dictum id aliquet vitae, maximus at tortor.</p>
<p>Suspendisse potenti. Maecenas eget metus et elit venenatis sagittis at non tortor. Nam sed magna hendrerit, feugiat justo quis, porta arcu. Morbi finibus dolor orci, eget vulputate lacus sagittis vitae. Proin non ex eu tortor venenatis commodo. Aliquam pulvinar lectus eu ligula porttitor luctus. Mauris luctus iaculis est in pulvinar. Maecenas purus est, ultricies eget mattis quis, dictum a libero.</p>
<?php
require $mainDir . "/includes/footer.php";
?>